name: Playwright Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    env:
      BASE_URL: ${{ secrets.BASE_URL }}
      API_URL: ${{ secrets.API_URL }}
      USERNAME: ${{ secrets.USERNAME }}
      PASSWORD: ${{ secrets.PASSWORD }}

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*

      - name: Install dependencies
        run: npm ci

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Detect changed tests
        id: changed-tests
        run: |
          TESTS=$(git diff --name-only origin/main...HEAD | grep '\.spec\.ts$' || true)

          echo "Changed tests:"
          echo "$TESTS"

          echo "TESTS<<EOF" >> $GITHUB_ENV
          echo "$TESTS" >> $GITHUB_ENV
          echo "EOF" >> $GITHUB_ENV

      - name: Run Playwright tests
        run: |
          if [ -z "$TESTS" ]; then
            echo "No changed tests found"
          else
            echo "Running tests:"
            echo "$TESTS"
            npx playwright test $TESTS
          fi

      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled() }}
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30